name: Sync Starter
on: [push]
#on:
#  schedule:
#    - cron: "14 20 * * 0"
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: Checkout files
    - name: Week Number
      id: week-number
      run: "echo \"::set-output name=week::$(date +%U)\""
    - name: Year Number
      id: year-number
      run: "echo \"::set-output name=year::$(date +%Y)\""
    - name: Adjust Package Versions
      run: .github/bump-version.sh ${{ steps.year-number.outputs.year }}-${{ steps.week-number.outputs.week }}
    - name: Debug output
      run: git --no-pager diff
    - run: yarn install
    - run: DEBUG_PROJECT_CREATION=true ./packages/pwa-buildpack/bin/buildpack create-project ../tmp-to-delete --template "venia-concept" --name "pwa-studio-canary" --author "Test Author<user@example.com>" --backend-url "https://master-7rqtwti-mfwmkrjfqvbjk.us-4.magentosite.cloud/" --braintree-token "sandbox_8yrzsvtm_s2bg8fs563crhqzk" --npm-client "yarn" --install 0
      name: Create packages
    - name: Retain package.json
      run: sed -i -e "s#file://$GITHUB_WORKSPACE/packages/#https://canary-packages.fooman.com/#g" $GITHUB_WORKSPACE/../tmp-to-delete/package.json
    - name: Git clone
      run:  git clone https://$GITHUB_ACTOR:$API_TOKEN_GITHUB@github.com/fooman/pwa-studio-starter.git $GITHUB_WORKSPACE/../starter/
    - name: Update code
      run: |
        cd $GITHUB_WORKSPACE/../starter/
        find . | grep -v ".git" | grep -v "^\.*$" | xargs rm -rf
        cp -r $GITHUB_WORKSPACE/../tmp-to-delete/. .
    - name: Push Changes
      run: |
              cd $GITHUB_WORKSPACE/../starter/
              git config --global user.name ${{ github.repository_owner }}
              git config --global user.email ${{ github.repository_owner }}'@users.noreply.github.com'
              if [ -n "$(git status --porcelain)" ]; then
                git add .
                git commit --message "Updated from upstream"
                git push origin main
              fi
